site_name: Xournal++
repo_url: https://github.com/xournalpp/xournalpp.github.io/
remote_branch: master
edit_uri: edit/site/docs
nav:
  - Install: installation.md
  - Guide:
      - Overview: guide/overview.md
      - Configuration: guide/config.md
      - Tools & Editing: guide/tools.md
      - Plugins: guide/plugins.md
      - Tips: guide/tips.md
  - "Report a bug": https://github.com/xournalpp/xournalpp/issues 
