site_name: Xournal++
repo_url: https://github.com/xournalpp/xournalpp.github.io/
remote_branch: master
edit_uri: edit/site/docs
nav:
  - Home: index.md
  - Install: installation.md
  - Guide: guide.md
